### ISSUE TITLE
Styling just the `Start` arrow

### ISSUE THREAD

**Issue by Quantumplation** [jneug/typst-finite#4]
Is it possible to change the label and/or apply a color to just the `Start` transition?

For example:
![image](https://github.com/jneug/typst-finite/assets/49870/4dd3434a-9338-4409-8017-609e19be5f2f)

In the first diagram, I've styled the `Active` state green, but it also applies to the incoming arrow.
And in the second diagram, I would like to style `Start` and the incoming arrow as green, without styling the state.

**Comment by jneug** [comment]
Right bow it is only possible to change the direction of the arrow and the text.

I will consider expanding this for a future release.

**Comment by jneug** [comment]
Have a look at the `initial` argument for `#state` on page 14. 
You will habe to draw the automaton manually with `#cetz.canvas`.

**Comment by jneug** [comment]
Seemed like an easy enough issue, so I added a styling option for initial states in [0.3.1](https://github.com/jneug/typst-finite/releases/tag/v0.3.1).

You can now do this:
```typst
#automaton(
  (
    "Active": ("Done": "Cancel", "Active": ""),
    "Done": ()
  ),
  layout: layout.linear.with(spacing: 3),
  style: (
    "transition": (curve: .5),
    "Active-Active": (curve: 1),
    "Active": (
      stroke: green,
      initial: (
        stroke: black
      )
    )
  )
)

#automaton(
  (
    "Locked": ("Unlockable": "StartTimer"),
    "Unlockable": ("Unlocked": "CancelTimer"),
    "Unlocked": ()
  ),
  layout: layout.linear.with(spacing: 3),
  style: (
    "transition": (curve: .5),
    "Locked": (
      initial: (
        stroke: green
      )
    )
  )
)
```

You need to get the version from this repository for now, since it is not yet in the package repository.
