### ISSUE TITLE
Missing i variable in powerset function

### ISSUE THREAD

**Issue by lz233** [jneug/typst-finite#8]
`powerset` function misses `i` variable, it causes a compiler error.

<img width="222" alt="image" src="https://github.com/user-attachments/assets/9236fda2-e68f-41b3-a157-df477662c7ed">

https://github.com/jneug/typst-finite/blob/6277ce1d868ff2912080dda19acdf925a88c141f/cmd.typ#L299

**Comment by jneug** [comment]
Sorry, missed this one for the 0.4.0 relase that just published. I submitted 0.4.1 with a fix for this.
